# Generated by Django 2.1.1 on 2018-09-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meryota', '0005_auto_20180923_0511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Cate',
        ),
    ]
